---
- hosts: all
  name: Create WordPress service
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Update packages
      yum: name=* state=latest
    - name: Install the Python MySQL module
      yum: name='MySQL-python' state=present
    - name: sshd config to accept pubkey
      lineinfile: dest="/etc/ssh/sshd_config" regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
      with_items:
        - { regexp: '^PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys' }
    - name: limits config for php
      lineinfile: dest="/etc/security/limits.conf" line="{{ item }}" state=present
      with_items:
        - '#<domain>   <type>  <item>  <value>'
        - '*           hard    nofile  1048576'
        - '*           soft    nofile  1048576'
        - 'root        hard    nofile  1048576'
        - 'root        soft    nofile  1048576'
- name: Install WordPress
  hosts: WordPress
  vars:
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: "www.example.com"
        documentroot: "/var/www/example"
        extra_parameters: |
              ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/example"
  roles:
#    - role: inmotionhosting.apache
#    - role: inmotionhosting.php_fpm
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - role: inmotionhosting.mysql
    - role: inmotionhosting.wordpress