---
- hosts: all
  name: Create WordPress service
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Update packages (this is equivalent to yum update -y)
      yum: name=* state=latest
    - name: Install the Python MySQLB module
      yum: name='MySQL-python' state=present
    - name: sshd config to accept pubkey PubkeyAuthentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '^%PubkeyAuthentication'
        line: '%PubkeyAuthentication yes'
    - name: sshd config to accept pubkey AuthorizedKeysFile
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '^%AuthorizedKeysFile'
        line: '%AuthorizedKeysFile .ssh/authorized_keys'
- name: Install WordPress
  hosts: WordPress
  roles:
    - role: inmotionhosting.apache
    - role: inmotionhosting.mysql
    - role: inmotionhosting.php_fpm
    - role: inmotionhosting.wordpress