---
- hosts: all
  name: Create WordPress service
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Update packages (this is equivalent to yum update -y)
      yum: name=* state=latest
    - name: Install the Python MySQL module
      yum: name='MySQL-python' state=present
    - name: sshd config to accept pubkey
      lineinfile: dest="/etc/ssh/sshd_config" regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
      with_items:
        - { regexp: '^%PubkeyAuthentication', line: '%PubkeyAuthentication yes' }
        - { regexp: '^%AuthorizedKeysFile', line: '%AuthorizedKeysFile .ssh/authorized_keys' }
    - name: limits config for php
      lineinfile:
        dest: /etc/security/limits.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: EOF
        state: present
      with_items:
        - { regexp: '', line: '#<domain>   <type>  <item>  <value>' }
        - { regexp: '', line: '*           hard    nofile  1048576' }
        - { regexp: '', line: '*           soft    nofile  1048576' }
        - { regexp: '', line: 'root        hard    nofile  1048576' }
        - { regexp: '', line: 'root        soft    nofile  1048576' }
- name: Install WordPress
  hosts: WordPress
  roles:
    - role: inmotionhosting.apache
    - role: inmotionhosting.mysql
    - role: inmotionhosting.php_fpm
    - role: inmotionhosting.wordpress