---
- hosts: all
  name: Initial host configuration
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Update packages
      yum: name=* state=latest
    - name: Install the Python MySQL module
      yum: name='MySQL-python' state=present
    - name: sshd config to accept pubkey
      lineinfile: dest="/etc/ssh/sshd_config" regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
      with_items:
        - { regexp: '^PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys' }
    - name: limits config
      lineinfile: dest="/etc/security/limits.conf" line="{{ item }}" state=present insertbefore='^# End of file'
      with_items:
        - '#<domain>   <type>  <item>  <value>'
        - '*           hard    nofile  1048576'
        - '*           soft    nofile  1048576'
        - 'root        hard    nofile  1048576'
        - 'root        soft    nofile  1048576'
- name: Install WordPress service
  hosts: WordPress
  roles:
    - inmotionhosting.apache
    - inmotionhosting.php_fpm
      vars:
        - php_ini_opcache_max_accelerated_files=1024
    - inmotionhosting.mysql
    - inmotionhosting.wordpress
