# Install a role from the Ansible Galaxy
- src: inmotionhosting.wordpress_ultrastack
#  src: inmotionhosting.apache
#  src: inmotionhosting.mysql
#  src: inmotionhosting.php_fpm
#  src: inmotionhosting.wordpress
#- collection: community.general
#- collection: ansible.posix