---
roles:
  # Install a role from Ansible Galaxy.
  - name: inmotionhosting.wordpress
  - name: inmotionhosting.apache
  - name: inmotionhosting.mysql
  - name: inmotionhosting.php_fpm
#  - name: ome.lvm_partition
#  - name: ome.docker
#  - name: ome.prometheus
  - name: lrk.prometheus

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
  - name: ansible.posix
